App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'

urlpatterns=[
    path("",views.BlogList.as_view(),name="blog_list"),
    path("write/",views.CreateBlog.as_view(),name="create_blog"),
    path("details/<slug:slug>",views.blog_details,name="blog_details"),
    path("liked/<pk>/", views.liked,name="liked_post"),
    path("unliked/<pk>/", views.unliked,name="unliked_post"),
    path("my_blogs/",views.MyBloges.as_view(),name="my_bloges"),
    path("edit_blog/<pk>/",views.UpdateBlog.as_view(),name="edit_blog"),

]

App_Login/urls.py
from django.urls import path
from App_Login import views

from django.conf import settings
# from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf.urls.static import static
app_name = 'App_Login'

urlpatterns=[
    path("",views.sign_up,name="signup"),
    path("login/",views.login_page,name="login"),
    path("logout/",views.logout_user,name="logout"),
    path("profile/",views.profile,name="profile"),
    path("change_profile/",views.user_chance,name="user_chance"),
    path("change_pass/",views.pass_change,name="pass_change"),
    path("add_picture/",views.upload_profile_picture,name="add_profile_pic"),
    path("change_picture/",views.change_profile_pic,name="change_profile_pic"),

]

djangoProject_My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    # path('',views.Index,name='index')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title> {% block title_block %} Blogs{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {#    <a class="navbar-brand" href="#">Navbar</a>#}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">


            {% if user.is_authenticated %}


                <li class="nav-item active">
                    <a class="nav-link" href="#">@{{ user.username }} <span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Blog:blog_list' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Blog:my_bloges' %}">My Blog <span
                            class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog <span
                            class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile <span
                            class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout <span
                            class="sr-only">(current)</span></a>
                </li>




                {#            {% if user.is_authenticated %}#}

{#                <div class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">#}
{#                        @{{ user.username }}#}
{##}
{#                    </a>#}
{#                    <div class="dropdown-menu">#}
{#                        <a class="dropdown-item" href="{% url 'App_Blog:my_bloges' %}">My Blog</a>#}
{#                        <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>#}
{#                        <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>#}
{#                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>#}
{##}
{#                    </div>#}
{##}
{#                </div>#}

            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
                </li>



            {% endif %}

        </ul>


    </div>


</nav>
<div class="container" style="padding-top:20px">
    {% block body %}

    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>


<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>


</body>
</html>

templates/blog_details.html
{% extends 'base.html' %}

{% block title_block %} {{ blog.blog_title }} {% endblock %}

{% block body %}
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'css/style4.css' %}">

    <div class="blog-details-container">
        <div class="blog-details-left">
            <h2>Title : {{ blog.blog_title }}</h2>
            <h4>Poster By: @{{ blog.author }}</h4>
            <i><p>Published On: {{ blog.publish_date }}</p></i>
{#            <i><h6>Updated On: {{ blog.update_date }}</h6></i>#}
            <br>
            <h6>Updated On: {{ blog.blog_content }}</h6>
            <br>
            <br>
            <h6>{{ blog.like.count }} Likes {{ blog.blog_comment.count }} Comment</h6>
            <p>{{ blog.blog|linebreaks }}</p>
            <hr>
            <div class="like-comment-container">
                {% if not liked %}
                <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
                    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
                </a>
                {% else %}
                <a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
                    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
                </a>
                {% endif %}
            </div>
            <div class="comments-section">
                <hr>
                <h5>Comments</h5>
                {% for comment in blog.blog_comment.all %}
                    <p class="comment"><a href="">@{{ comment.user }}</a> ----> {{ comment.comment }}  </p>
                    <p>{{ comment.comment_date }}</p>
                {% endfor %}
            </div>
        </div>
        
        <div class="blog-details-right">
            <img class="blog-image" src="{{ blog.blog_image.url }}">
            <div class="comment-form-container">
                <form method="POST">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm"> Comment</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog_list.html
<!-- index.html -->

{% extends 'base.html' %}

{% block title_block %} Home {% endblock %}

{% block body %}
    {% load static %}

    <!-- Include a CSS stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style_2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style4.css' %}">
    <link rel="stylesheet" href="{% static 'css/copy.css' %}">

    <h1>This is Blog Page</h1>

    <div class="blog-container">
        <!-- Loop through the list of blogs -->
        {% for blog in blogs %}
            {% if forloop.counter0|divisibleby:3 %}
                </div>
                <div class="blog-row">
            {% endif %}
            
            <div class="blog">
                <!-- Display the blog image -->
                <img src="{{ blog.blog_image.url }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%">
                
                <!-- Display a portion of the blog content with linebreaks -->
                <div class="blog-content">
                    <h2>{{ blog.blog_title }}</h2>
                    <i><h6>{{ blog.publish_date }}</h6></i>
                    <p>{{ blog.blog_content|truncatechars:150|linebreaks }}</p>
                    <!-- Adjust the number in truncatechars to control the length of the displayed content -->
                    <h6>Posted By: <a href="">{{ blog.author }}</a></h6>
                    <!-- Display the number of likes and comments -->
                    <h6>{{ blog.like.count }} Likes {{ blog.blog_comment.count }} Comments</h6>
                    <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
                </div>
            </div>
            
            {% if forloop.last %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/change_pass.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% if changed %}
    <div class="alert alert-success">
    Passowrd change successfully !
    </div>
    {%  endif %}
    <h1>password:</h1>
    <form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change</button>
    </form>

{% endblock %}

templates/change_profile.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>Change your Profile:</h1>
    <form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change</button>
    <a href="{% url 'App_Login:pass_change' %}" class="btn btn-warning btn-sm">Change Password</a>


    </form>

{% endblock %}

templates/create_blog.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>Write Your Blog Here:</h1>
    <form method="POST" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button class="btn btn-success btn-sm">Publish</button>

    </form>

{% endblock %}

templates/edit_blog.html
{% extends 'base.html' %}
{% block title_block %} {{ blog.blog_title }} {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>Edit Your Blog</h1>

{#    {% if blog.author==user %}#}
    <form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" name="button">Update</button>
{#    {% else %}#}
{#    <p>You are not allow to update this page</p>#}
    </form>
{#    {% endif %}#}

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style1.css' %}">

    <h1>Login Here</h1>

    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Login</button>

{% endblock %}

templates/my_blogs.html
{% extends 'base.html' %}

{% block title_block %} {{ user }} {% endblock %}

{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>My Blogs</h1>
    {% for blog in user.post_author.all %}
        <div class="blog-container">
            <div class="blog-content">
                <h3>{{ blog.blog_title }}</h3>
                <h3>{{ blog.publish_date }}</h3>
                <p>{{ blog.blog_content|linebreaks }}</p>
                <div class="center-links">
                    <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}" class="btn btn-read-more">Read More</a>
                    <a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}" class="btn btn-edit">Edit</a>
                </div>
            </div>
            <div class="blog-image">
                <img src="{{ blog.blog_image.url }}" width="100%" alt="{{ blog.blog_title }}">
            </div>
        </div>
        <hr>
    {% endfor %}

{% endblock %}
 

templates/profile.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>Your Profile</h1>
    {% if user.profile_picture.image.url %}
    <img class="rounded-circle account-img" style="width: 80px; height: 80px" src="{{ user.profile_picture.image.url }}">

    <br>
    <br>
    <a href="{% url 'App_Login:change_profile_pic' %}" class="btn btn-info btn-sm">Change profile Pic</a>

    {% else %}
    <img src="/media/profile_pics/1.jpg " class="rounded-circle" width="100px">
    <br>
    <br>
    <br>
    <a href="{% url 'App_Login:add_profile_pic' %}" class="btn btn-info btn-sm">Upload Profile</a>

    {% endif %}
    <br>
    <br>

    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p> Name: {{ user.first_name }} {{ user.last_name }}</p>
    <br>
    <br>

    <a href="{% url 'App_Login:user_chance' %}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}

templates/profile_pic_add.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body %}
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>Add Your Profile Picture</h1>
    <form method="POST" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm"> Add </button>

    </form>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title_block %} Create a new account {% endblock %}
{% block body %}

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% if registered %}
        <div class="alert alert-success">
            Account Created Successfully <a href="{% url 'App_Login:login' %}">Login Here</a>
        </div>
    {% else %}
        <div class="center">
            <h1>Create a new account:</h1>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <div class="text-center"> <!-- Add text-center class for centering -->
                    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
                </div>
                <br>
                <p>Already have an account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
            </form>
        </div>
    {% endif %}
{% endblock %}